### ISSUE TITLE
主题

### ISSUE THREAD

**Issue by Logimans** [probberechts/hexo-theme-cactus#109]
我想问一下主页上面的Find me on  and 这句话的配置在哪里 就是这句话的文件位置
![wechat screenshot_20180719210224](https://user-images.githubusercontent.com/34396774/42944123-63796e84-8b97-11e8-9619-973ba320011a.png)

**Comment by probberechts** [comment]
It can be configured using the following configuration variables:
```yaml
# Links to your social media accounts.
# The keys should correspond to Fontawesome icon names 
# (see https://fontawesome.com/icons?d=gallery&s=brands);
# only 'mail' is an exception.
social_links:
  github: http://github.com/probberechts/cactus-dark
  twitter: /
  facebook: /
  linkedin: /
  mail: mailto:name@email.com
```
