### ISSUE TITLE
sort_updated

### ISSUE THREAD

**Issue by h0ek** [probberechts/hexo-theme-cactus#149]
```
posts_overview:
  show_all_posts: false
  post_count: 5
  sort_updated: true

archive:
  sort_updated: false
```
This option doesn't work. It sort posts on main page by update date but it is doing the same thing on archive page, even when archive option is set to false. Could you please fix that?
