### ISSUE TITLE
I think there are missing some info in the README

### ISSUE THREAD

**Issue by jiangjiji** [probberechts/hexo-theme-cactus#153]
I think the info of _how to create Tags and categories_ are missing some important message.

> Tags and categories

After create page tags or categories, it also need edit the _config.yml and add a link to the navigation menu.

```
nav:
  tags: /tags/
  categories: /categories/
```

BTW, I want to add some chinese translation, but I'm a little confuse about _counter_  node. What are the one _node_ and the _other_ node using for?  You can see there are null node and whitout any notes to explain.

```
counter:
  tag_cloud:
    zero: No tags
    one: ""
    other: ""

  categories:
    zero: No categories
    one: ""
    other: ""

  archive_posts:
    zero: No posts.
    one: ""
    other: ""
```
