### ISSUE TITLE
TOC links are #undefined

### ISSUE THREAD

**Issue by zachgoll** [probberechts/hexo-theme-cactus#155]
I have experienced an issue where all of my TOC links show as #undefined.  I do not think this is an issue directly related to the Cactus Theme but was hoping I could get some more insight into how the TOC is implemented in hexo.  Here is my package.json and _config.yml

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.2"
  },
  "devDependencies": {
    "hexo": "^3.8.0"
  }
}
```

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "Zach Gollwitzer"
subtitle: "My Blog"
description: "fintech. software. books."
author: "Zach Gollwitzer"
language: EN
timezone: "America/Chicago"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://zachgoll.github.io/blog
root: /blog/
permalink: :year/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/zachgoll/blog.git
  branch: gh-pages
  message: "Add blog post"
```

Feel free to see what I am talking about by visiting one of my posts - https://zachgoll.github.io/blog/2019/how-to-code-crash-course/

**Comment by zachgoll** [comment]
Found a solution, although it is not completely ideal.  I found that my issue was the [hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it) plugin.  It was not properly generating the links.  I completely removed this plugin (as shown in my issue above), added the `hexo-renderer-marked` plugin with `npm install --save hexo-renderer-marked`, and then added the following to my `_config.yml`.

```
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
  modifyAnchors: ''
  autolink: true
```
