### ISSUE TITLE
how to changing "tags, categories language"

### ISSUE THREAD

**Issue by jisng** [probberechts/hexo-theme-cactus#201]
Hi,
I created 'kr.yml' and setting 'language/default.yml'
but didn't changed 'tags' and 'categories' languages
Can you help me?

**Comment by probberechts** [comment]
I'm not sure whether you refer to the literal words "tags" and "categories" that appear on some page (I do not know where though, help me out) or the tags and categories that you use in the front matter of your posts. The latter are not translated automatically. You have to use Korean tags and categories if your website is in Korean.

**Comment by jisng** [comment]
<img width="507" alt="스크린샷 2019-11-20 오후 2 34 50" src="https://user-images.githubusercontent.com/37435497/69211885-eb639180-0ba2-11ea-8efd-cfa299adbe73.png">

Why not translated "tags" and "categories" ?


default.yml  ↓
```
nav:
  home: 홈
  about: 소개
  articles: 목록
  tag: 태그
  category: 카테고리
  projects: 프로젝트
  search: 검색

footer:
  copyright: 저작권

index:
  find_me_on: 찾기
  enum_comma: ','
  enum_and: 그리고
  articles: 목록
  projects: 프로젝트
  topics: 주제
  most_recent: 가장 최근

post:
  desktop:
    previous: 이전
    next: 다음
    back_to_top: 맨 위로
    share: 공유
  mobile:
    menu: 메뉴
    toc: TOC
    back_to_top: 맨 위로
    share: 공유

search:
  search: 검색중...
  no_results: 검색 결과가 없습니다.

tag_cloud:
  zero: 태그가 없습니다.

pagination:
  page: 총 %쪽 중 %쪽

counter:
  tag_cloud:
    zero: 태그가 없습니다.
    one: ""
    other: ""

  categories:
    zero: 카테고리가 없습니다.
    one: ""
    other: ""

  archive_posts:
    zero: 등록된 글이 없습니다.
    one: ""
    other: ""

comments:
  no_js: 코멘트를 보려면 자바스크립트를 활성화하세요.

tooltip:
  copy_tip: 클립보드에 복사하였습니다!
  copied: 복사하였습니다!
```
