### ISSUE TITLE
Add social_links in Root's _config.yml not working

### ISSUE THREAD

**Issue by FledgeXu** [probberechts/hexo-theme-cactus#220]
![image](https://user-images.githubusercontent.com/16664654/73849480-faceae80-4864-11ea-94e1-2dd2e1429845.png)
I added my social_links in the root *_config.yml*, but it didn't replace  the original social_links in the theme.
![image](https://user-images.githubusercontent.com/16664654/73849859-9d872d00-4865-11ea-8726-3014b0fea84c.png)
![image](https://user-images.githubusercontent.com/16664654/73849879-a7109500-4865-11ea-8342-122182547817.png)

**Comment by probberechts** [comment]
This is documented in the README. You either have to edit the theme's config file or define your custom settings under the `theme_config` variable. For example:
```yml
# _config.yml
theme_config:
  social_links: http://www.github.com/probberechts
```
