### ISSUE TITLE
Social Links Formatting: Spacing does not work properly sometimes

### ISSUE THREAD

**Issue by metters** [probberechts/hexo-theme-cactus#310]
The spacing between social links sometimes seems broken.
For example, there might be a whitespace between the last fontawesome and the fullstop:
<img width="664" alt="Screenshot 2022-04-10 at 08 10 51" src="https://user-images.githubusercontent.com/9088722/162605287-d7f942fa-9897-4bb2-9ebd-2ff42fb1c9be.png">

Sometimes the whitespace is missing, which i found in a blog, not belonging to me:
<img width="384" alt="Screenshot 2022-04-10 at 08 11 03" src="https://user-images.githubusercontent.com/9088722/162605323-75a2886e-7d34-4f9d-95bd-e1c18c49771a.png">

In my own example,`social_links` was configured like this:
```yaml
social_links:
  github: https://github.com/john_doe
  xing: https://www.xing.com/profile/John_Doe
  mail: mailto:john.doe@example.org
```
If I change the order the issue disappears. I believe it is not the content of the links alone that determines whether the spacing/formatting works properly. Thus, there should be some other aspect responsible for the bug besides the order of the links.

I only configured the three links of my deployed example, the rest was just a newly initiated hexo-blog with the cactus template., which means the steps to recreate this are described in the [readme](https://github.com/probberechts/hexo-theme-cactus#readme) file.
