### ISSUE TITLE
Add lightgallery

### ISSUE THREAD

**Issue by punksinatra** [probberechts/hexo-theme-cactus#70]
Hi,

Any ideas how to make [lightgallery](https://www.npmjs.com/package/hexo-light-gallery) work?

**Comment by probberechts** [comment]
I got it working with the following steps:

1. Install hexo-light-gallery

```bash
npm install --save hexo-light-gallery
```

2. Append the following to `_config.yml`

```yml
lightgallery:
  css: https://cdn.jsdelivr.net/lightgallery.js/1.0.1/css/lightgallery.min.css
  js: https://cdn.jsdelivr.net/lightgallery.js/1.0.1/js/lightgallery.min.js
```

3. Run `hexo clean && hexo generate`.
4. And 💥! It works automatically for all images.
